<?php
	/**
	 * @author Mikulas Dite, Peter Ped Helcmanovsky
	 */
?>

<h1>{$todocount}&times;TODO (in {=count($todos)} files)</h1>

<div class="nette-inner">
	<table style="width: 100%;">
		<thead>
			<tr>
				<th>File</th>
				<th>Line</th>
				{if $showType}<th>Type</th>{/if}
				<th>Todo</th>
			</tr>
		</thead>
		<tbody>
			{foreach $todos as $file => $t}
				{assign filename => basename($file)}
				<tr n:foreach="$t as $line => $todo">
					<td n:if="$iterator->first" rowspan="{=count($t)}" title="{$file}">{$filename}</td>
					<td style="text-align: right; color: #777;">{$line}</td>
					{if $showType}<td style="color: #777;">{$todo['type']}</td>{/if}
					<td{if $todo['color']} style="color: {!$todo['color']}"{/if}>{$todo['txt']}</td>
				</tr>
			{/foreach}
		</tbody>
	</table>
</div>
