<?php
	/**
	 * @author Mikulas Dite, Peter Ped Helcmanovsky
	 */
?>

<h1>Todo</h1>

<div class="nette-inner">
	<table style="width: 100%;">
		<thead>
			<tr>
				<th>File</th>
				<th>Line</th>
				<th>Todo</th>
			</tr>
		</thead>
		<tbody>
			{foreach $todos as $file => $t}
				{assign filename => basename($file)}
				<tr n:foreach="$t as $line => $todo">
					<td n:if="$iterator->first" rowspan="{=count($t)}" title="{$file}">{$filename}</td>
					<td style="text-align: right; color: #777;">{$line}</td>
					<td>{$todo}</td>
				</tr>
			{/foreach}
		</tbody>
	</table>
</div>
